# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasanswered',
            name='firstWasCorrect',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
