# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_hasanswered_firstwascorrect'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/questions'),
        ),
    ]
