# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question_text',
            new_name='choice_text',
        ),
    ]
