# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasanswered',
            name='answer_attempt',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='test_attempt',
            field=models.IntegerField(default=1),
        ),
    ]
