# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20170307_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='test_attempt',
        ),
        migrations.AddField(
            model_name='haschapter',
            name='chapter_attempt',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=700),
        ),
    ]
